# probe adb phone - no sparkpulse yet
$adb = "$env:LOCALAPPDATA\Android\Sdk\platform-tools\adb.exe"
$dev = "oneplus-15r:5555"
Write-Host "=== devices ==="
& $adb devices -l
Write-Host ""
Write-Host "=== shell test ==="
& $adb -s $dev shell "getprop ro.product.model; getprop ro.build.version.release; getprop ro.product.brand"
Write-Host ""
Write-Host "=== installed spark/forge/pulse packages ==="
& $adb -s $dev shell pm list packages | Select-String -Pattern "spark", "forge", "pulse"
Write-Host ""
Write-Host "=== installed count ==="
& $adb -s $dev shell pm list packages | Measure-Object -Line
Write-Host ""
Write-Host "=== sparkpulse-app on DGX: exists? ==="
ssh dgx "ls /home/jagones/Repositories/sparkpulse-app/ 2>&1 | head -30"
Write-Host ""
Write-Host "=== build outputs? ==="
ssh dgx "find /home/jagones/Repositories/sparkpulse-app -maxdepth 5 -name '*.apk' 2>&1 | head -10"
