#!/usr/bin/env python3
"""SparkForge v0.6 — per-run task graph, generated by the LLM (write_todos).

Modern harnesses (Claude Code Agent SDK todo-tracking, Deep Agents write_todos)
keep a *live, per-run* graph of the steps the model itself decided on, instead of
a static global list disconnected from the conversation. This module owns that
graph:

  * one graph per run  → `data/graphs/<run_id>.json`, linked to `session_id`
    and `run_id` (nodes: id, label, status todo|doing|done|blocked|cancelled,
    deps[], evidence[]);
  * the first action of any chat/agent run is a model-generated
    `write_todos` tool call (streamed, NDJSON or nested JSON — never a template);
  * every mutation emits `graph.node.added` / `graph.node.updated` on the feed,
    so WebUI and SparkPulse render the graph live;
  * a node may only become `done` when it carries evidence (command + output);
  * `plan_step` / `complete_plan_step` / `add_task` / `complete_task` from the
    existing agent loops are mapped onto graph nodes.

server.py owns the HTTP surface (`GET /api/runs/<id>/graph`,
`POST /api/runs/<id>/graph/nodes`); this module stays server-agnostic and
imports `server` lazily only to publish events.
"""

import json
import os
import re
import threading
import time
import uuid

REPO = os.path.dirname(os.path.abspath(__file__))
GRAPH_DIR = os.path.join(os.environ.get("SPARKFORGE_GRAPH_DIR", os.path.join(REPO, "data")),
                         "graphs")

GRAPH_LOCK = threading.RLock()
STATUSES = ("todo", "doing", "done", "blocked", "cancelled")
OPEN_STATUSES = ("todo", "doing", "blocked")

# The model is asked to answer the FIRST action of every run with this tool call.
# Two wire formats are accepted, both stream-friendly:
#   NDJSON:   {"tool":"write_todos"}\n{"label":"...","deps":[]}\n{"label":"...","deps":[0]}
#   nested:   {"tool":"write_todos","todos":[{"label":"...","deps":[]}, ...]}
WRITE_TODOS_PROMPT = (
    "You are the SparkForge planner. Your FIRST action for every request is to "
    "call the `write_todos` tool: decompose the current user request into an "
    "ordered task graph of 2-6 steps. Respond with ONLY JSON, one object per "
    "line (no prose, no markdown):\n"
    '{"tool":"write_todos"}\n'
    '{"label":"<imperative step specific to the request>","status":"todo","deps":[]}\n'
    '{"label":"<next step>","status":"todo","deps":[0]}\n'
    "Rules: labels are imperative and mention the actual request (never generic "
    "placeholders); `deps` holds the 0-based indices of prerequisite todos; the "
    "first step has no dependencies. A single JSON object with a `todos` array "
    "is also accepted."
)


# ------------------------------------------------------------- publishing --

def _publish(kind, **data):
    """Fan out to the harness feed; never let the feed break a run."""
    try:
        import server
        return server.publish(kind, **data)
    except Exception:  # noqa: BLE001
        return None


# ------------------------------------------------------------------ storage --

def _safe_id(run_id):
    return re.sub(r"[^A-Za-z0-9_.-]", "_", str(run_id or "unknown"))[:96]


def _path(run_id):
    return os.path.join(GRAPH_DIR, _safe_id(run_id) + ".json")


def _read_json(path, default=None):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:  # noqa: BLE001
        return default


def _write_json(path, obj):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=2, ensure_ascii=False)
    os.replace(tmp, path)


def load(run_id):
    """Load one run graph (dict) or None."""
    return _read_json(_path(run_id), None)


def save(graph):
    graph["updated"] = round(time.time(), 3)
    _write_json(_path(graph["run_id"]), graph)
    return graph


def ensure(run_id, session_id=None, goal=None):
    """Get-or-create the graph for a run, tagged with session_id + run_id."""
    with GRAPH_LOCK:
        g = load(run_id)
        if g is None:
            g = {"run_id": run_id, "session_id": session_id, "goal": goal,
                 "nodes": [], "created": round(time.time(), 3),
                 "updated": round(time.time(), 3), "generated": False}
            save(g)
        else:
            changed = False
            if session_id and g.get("session_id") != session_id:
                g["session_id"] = session_id
                changed = True
            if goal and g.get("goal") != goal:
                g["goal"] = goal
                changed = True
            if changed:
                save(g)
        return g


def counts(graph):
    c = {s: 0 for s in STATUSES}
    for n in graph.get("nodes", []):
        c[n.get("status", "todo")] = c.get(n.get("status", "todo"), 0) + 1
    return c


def public(graph):
    """UI-friendly shape: nodes + counts + a coarse graph status."""
    if not graph:
        return None
    c = counts(graph)
    total = len(graph.get("nodes", []))
    if total and c.get("done") == total:
        status = "done"
    elif any(n.get("status") == "blocked" for n in graph.get("nodes", [])):
        status = "blocked"
    elif c.get("doing"):
        status = "doing"
    elif total:
        status = "todo"
    else:
        status = "empty"
    return {**graph, "counts": c, "status": status, "node_count": total}


def _next_id(graph):
    used = {n["id"] for n in graph.get("nodes", [])}
    i = 1
    while ("n%d" % i) in used:
        i += 1
    return "n%d" % i


def _evidence_entry(text, **extra):
    entry = {"ts": round(time.time(), 3), "text": str(text)[:4000]}
    entry.update({k: v for k, v in extra.items() if v is not None})
    return entry


def _has_evidence(node):
    return bool([e for e in (node.get("evidence") or []) if (e.get("text") or "").strip()])


# ------------------------------------------------------------ node mutation --

def add_node(graph, label, deps=None, status="todo", evidence=None, node_id=None,
             source="model"):
    """Append a node; emits `graph.node.added`. `done` requires evidence."""
    label = str(label or "").strip()[:200]
    if not label:
        raise ValueError("label required")
    if status not in STATUSES:
        raise ValueError("bad status %r (expected one of %s)" % (status, ", ".join(STATUSES)))
    deps = [str(d) for d in (deps or []) if str(d)]
    ev = []
    if evidence:
        ev = list(evidence) if isinstance(evidence, list) else [_evidence_entry(evidence)]
    if status == "done" and not ev:
        raise ValueError("evidence required for a node in status 'done'")
    node = {"id": node_id or _next_id(graph), "label": label, "status": status,
            "deps": deps, "evidence": ev, "source": source,
            "created": round(time.time(), 3), "updated": round(time.time(), 3)}
    with GRAPH_LOCK:
        graph["nodes"].append(node)
        save(graph)
    _publish("graph.node.added", run=graph["run_id"], session=graph.get("session_id"),
             node=node, index=len(graph["nodes"]) - 1, total=len(graph["nodes"]))
    return node


def find(graph, node_id=None, label=None):
    for n in graph.get("nodes", []):
        if node_id and n["id"] == node_id:
            return n
    if label:
        for n in graph.get("nodes", []):
            if n["label"].lower() == str(label).strip().lower():
                return n
    return None


def update_node(graph, node_id, evidence=None, source=None, **fields):
    """Patch a node; emits `graph.node.updated`. Evidence is mandatory for `done`."""
    node = find(graph, node_id)
    if node is None:
        raise KeyError("node %r not found" % node_id)
    changes = {}
    if "status" in fields and fields["status"] is not None:
        st = fields["status"]
        if st not in STATUSES:
            raise ValueError("bad status %r (expected one of %s)" % (st, ", ".join(STATUSES)))
        changes["status"] = st
    if fields.get("label"):
        changes["label"] = str(fields["label"])[:200]
    if fields.get("deps") is not None:
        changes["deps"] = [str(d) for d in fields["deps"]]
    if source:
        changes["source"] = source
    if evidence:
        entries = evidence if isinstance(evidence, list) else [_evidence_entry(evidence)]
        changes["evidence"] = list(node.get("evidence") or []) + entries
    # A node can only be marked done with evidence on the node (old or new).
    if changes.get("status") == "done":
        probe = {**node, **changes}
        if not _has_evidence(probe):
            raise ValueError("evidence required to mark node %s done" % node_id)
    with GRAPH_LOCK:
        node.update(changes)
        node["updated"] = round(time.time(), 3)
        save(graph)
    _publish("graph.node.updated", run=graph["run_id"], session=graph.get("session_id"),
             node=node, changes=sorted(changes.keys()))
    return node


def complete_node(graph, node_id=None, label=None, evidence=None, source=None):
    """Mark a node done (creating it from the label when it is unknown)."""
    node = find(graph, node_id, label)
    if node is None and label:
        node = add_node(graph, label, source=source or "action")
    if node is None:
        raise KeyError("node %r not found" % (node_id or label))
    ev = evidence or "completed by agent"
    return update_node(graph, node["id"], status="done", evidence=ev, source=source)


def cancel_node(graph, node_id):
    """Cancel (soft-delete) a node — never silently drop history."""
    return update_node(graph, node_id, status="cancelled", source="cancel")


def apply_write_todos(graph, todos, source="model:write_todos", index_map=None, start=0):
    """Turn a parsed `write_todos` payload into graph nodes (order preserved).

    `deps` are 0-based indices into the todo list; `index_map` (index → node id)
    lets callers feed the list one line at a time and still resolve deps.
    """
    added = []
    index_map = index_map if index_map is not None else {}
    for i, item in enumerate(todos or []):
        if isinstance(item, str):
            item = {"label": item}
        if not isinstance(item, dict):
            continue
        label = item.get("label") or item.get("title") or item.get("task")
        if not label:
            continue
        deps = []
        for d in (item.get("deps") or item.get("depends_on") or []):
            if isinstance(d, bool):
                continue
            if isinstance(d, int) and d in index_map:
                deps.append(index_map[d])
            elif isinstance(d, str) and d.isdigit() and int(d) in index_map:
                deps.append(index_map[int(d)])
            elif isinstance(d, str) and d:
                existing = find(graph, label=d)
                if existing:
                    deps.append(existing["id"])
        status = item.get("status") if item.get("status") in STATUSES else "todo"
        evidence = item.get("evidence")
        if status == "done" and not evidence:
            status = "todo"
        node = add_node(graph, label, deps=deps, status=status, evidence=evidence,
                        source=source)
        index_map[start + i] = node["id"]
        added.append(node)
    graph["generated"] = True
    save(graph)
    return added


def finalize(graph, evidence, only_open=True):
    """At run end, close every open node with evidence (acceptance: all done)."""
    closed = []
    for n in list(graph.get("nodes", [])):
        if only_open and n.get("status") not in OPEN_STATUSES:
            continue
        try:
            closed.append(update_node(graph, n["id"], status="done",
                                      evidence=evidence, source="run-finalize"))
        except (KeyError, ValueError):
            continue
    return closed


# ----------------------------------------------- model-generated first action --

def _iter_json_objects(text):
    """All balanced top-level `{...}` objects in `text` (order preserved)."""
    objs, depth, start, in_str, esc = [], 0, None, False, False
    for i, ch in enumerate(text):
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    try:
                        objs.append(json.loads(text[start:i + 1]))
                    except Exception:  # noqa: BLE001
                        pass
    return objs


def parse_todos(text):
    """Parse `write_todos` output from NDJSON lines and/or a nested JSON object."""
    todos, saw_tool = [], False
    for obj in _iter_json_objects(text or ""):
        if not isinstance(obj, dict):
            continue
        if obj.get("tool") == "write_todos" or "todos" in obj:
            saw_tool = True
            nested = obj.get("todos")
            if isinstance(nested, list):
                todos.extend(nested)
            continue
        if obj.get("label") or obj.get("title") or obj.get("task"):
            todos.append(obj)
    return todos, saw_tool


class _TodoStream:
    """Incremental NDJSON consumer: emits each todo the moment its line lands."""

    def __init__(self, graph, on_event=None, source="model:write_todos",
                 skip_existing=False):
        self.graph = graph
        self.on_event = on_event
        self.source = source
        self.skip_existing = skip_existing
        self.index_map = {}   # todo index → node id (deps resolve across lines)
        self.count = 0
        self.buf = ""
        self.got = False
        self.added = []

    def _emit(self, node):
        self.added.append(node)
        if self.on_event:
            try:
                self.on_event("graph.node.added", run=self.graph["run_id"],
                              session=self.graph.get("session_id"), node=node,
                              index=len(self.added) - 1, total=len(self.added))
            except Exception:  # noqa: BLE001
                pass

    def _consume(self, line):
        line = (line or "").strip().rstrip(",")
        if not line.startswith("{"):
            return
        try:
            obj = json.loads(line)
        except Exception:  # noqa: BLE001
            return
        if not isinstance(obj, dict):
            return
        if isinstance(obj.get("todos"), list):
            nested = self._dedupe(obj["todos"])
            for t in apply_write_todos(self.graph, nested, self.source,
                                       index_map=self.index_map, start=self.count):
                self._emit(t)
            self.count += len(nested)
            return
        if obj.get("tool") == "write_todos" and not (
                obj.get("label") or obj.get("title") or obj.get("task")):
            return
        if obj.get("label") or obj.get("title") or obj.get("task"):
            for t in apply_write_todos(self.graph, self._dedupe([obj]), self.source,
                                       index_map=self.index_map, start=self.count):
                self._emit(t)
            self.count += 1

    def _dedupe(self, todos):
        # re-plan: never duplicate a label that is already on the graph
        return _missing(self.graph, todos) if self.skip_existing else todos

    def feed(self, text):
        """Consume a stream *delta*; each complete ("\\n"-terminated) line is a todo."""
        text = text or ""
        if text:
            self.got = True
        self.buf += text
        lines = self.buf.split("\n")
        self.buf = lines.pop()
        for line in lines:
            self._consume(line)
        return self.added

    def flush(self):
        """Flush whatever is left in the buffer (no trailing newline)."""
        tail, self.buf = self.buf, ""
        if tail.strip():
            self._consume(tail)
        return self.added


def _missing(graph, todos):
    """Drop todos whose label already exists on the graph (idempotent re-parse)."""
    seen = {n["label"].strip().lower() for n in graph.get("nodes", [])}
    out = []
    for t in todos or []:
        label = t if isinstance(t, str) else (t.get("label") or t.get("title") or t.get("task"))
        key = str(label or "").strip().lower()
        if key and key not in seen:
            seen.add(key)
            out.append(t)
    return out


def generate_from_model(run_id, goal, session_id=None, model=None, on_event=None):
    """First action of the run: ask the model for a `write_todos` call.

    Streams the reply and adds each node to the graph as soon as its line is
    complete, publishing `graph.node.added` live. Returns (graph, added_nodes).
    If the graph already has nodes the first action already ran → no-op.
    """
    import server as srv
    graph = ensure(run_id, session_id=session_id, goal=goal)
    if graph.get("nodes"):
        return graph, []
    stream = _TodoStream(graph, on_event=on_event)
    msgs = [{"role": "system", "content": srv.SYSTEM_PROMPT + "\n\n" + WRITE_TODOS_PROMPT},
            {"role": "user", "content": goal}]
    m = model
    if not m:
        try:
            import routing
            m = routing.pick("planner")
        except Exception:  # noqa: BLE001
            m = None
    m = m or srv.default_model()

    def on_delta(channel, text):
        if channel == "think" or not text:
            return
        try:
            stream.feed(text)
        except Exception:  # noqa: BLE001
            pass

    answer, _think = srv._router_stream(msgs, m, on_delta)
    if not stream.got:  # no deltas (non-streaming path) → consume the answer once
        stream.feed(answer)
    stream.flush()
    if not stream.added:  # pretty-printed / nested JSON that never formed a line
        for node in apply_write_todos(graph, _missing(graph, parse_todos(answer)[0])):
            stream._emit(node)
    graph["generated"] = graph.get("generated") or bool(stream.added)
    save(graph)
    _publish("graph.generated", run=graph["run_id"], session=graph.get("session_id"),
             goal=goal, nodes=len(graph.get("nodes", [])), model=m)
    return graph, stream.added


def replan_from_model(graph, note=None, model=None, on_event=None):
    """Incremental re-plan: the model proposes only the steps still missing.

    Used by `POST /api/runs/<id>/graph/nodes {action:"replan"}` when the request
    changes or a step turns out to be blocked. Existing nodes are preserved.
    """
    import server as srv
    existing = [n["label"] for n in graph.get("nodes", []) if n.get("status") != "cancelled"]
    prompt = (WRITE_TODOS_PROMPT + "\n\nThe task graph already contains: " +
              json.dumps(existing, ensure_ascii=False) +
              "\nEmit ONLY the NEW steps still missing (never repeat an existing label).")
    msgs = [{"role": "system", "content": srv.SYSTEM_PROMPT + "\n\n" + prompt},
            {"role": "user", "content": note or graph.get("goal") or "continue"}]
    m = model
    if not m:
        try:
            import routing
            m = routing.pick("planner")
        except Exception:  # noqa: BLE001
            m = None
    m = m or srv.default_model()
    stream = _TodoStream(graph, on_event=on_event, source="model:replan",
                         skip_existing=True)

    def on_delta(channel, text):
        if channel != "think" and text:
            try:
                stream.feed(text)
            except Exception:  # noqa: BLE001
                pass

    answer, _think = srv._router_stream(msgs, m, on_delta)
    if not stream.got:
        stream.feed(answer)
    stream.flush()
    if not stream.added:
        for node in apply_write_todos(graph, _missing(graph, parse_todos(answer)[0]),
                                      "model:replan"):
            stream._emit(node)
    save(graph)
    _publish("graph.replanned", run=graph["run_id"], session=graph.get("session_id"),
             added=len(stream.added), nodes=len(graph.get("nodes", [])))
    return stream.added


# --------------------------------------------- existing-action → node mapping --

def map_action(run_id, act, observation=None, session_id=None, goal=None):
    """Map a legacy agent action onto the run graph.

    plan_step/complete_plan_step/add_task/complete_task → nodes + status, and
    `write_todos` → the full model-generated graph. Returns the touched node
    (or None).
    """
    action = (act or {}).get("action")
    if action not in ("plan_step", "complete_plan_step", "add_task", "complete_task",
                      "write_todos"):
        return None
    graph = ensure(run_id, session_id=session_id, goal=goal)
    evidence = observation or None
    if action == "write_todos":
        todos = act.get("todos")
        if isinstance(todos, str):
            todos, _ = parse_todos(todos)
        return apply_write_todos(graph, todos or [])
    label = act.get("title") or act.get("label") or act.get("detail")
    if action in ("plan_step", "add_task"):
        if not label:
            return None
        return add_node(graph, label, source="action:" + action)
    # completion actions
    node = find(graph, node_id=act.get("id"), label=label)
    try:
        return complete_node(graph, node_id=act.get("id"), label=label,
                             evidence=evidence or "completed: %s" % (label or act.get("id")),
                             source="action:" + action)
    except (KeyError, ValueError):
        return None
