#!/usr/bin/env python3
"""v251 — wire type-confusion on the settings surface (/api/tools) and on
rules.save (JAG-251).

The Config panel posts settings as JSON. A non-numeric value (a string, a list)
reached `int()`/`float()`/`list()` unguarded, raised out of the handler, and the
HTTP layer DROPPED the connection (no response). `rules.save` also wrote `content`
straight to disk and called `len(content)`.

Deterministic, no live server, no network, and NEVER touches the live config:
SPARKFORGE_CONFIG_DIR / sessions / provider overlay are redirected to a temp dir.
Run:  python3 tests/v251_settings_wire.py
"""
import json
import os
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TMP = tempfile.mkdtemp(prefix="sf-v251-")
os.environ["SPARKFORGE_CONFIG_DIR"] = os.path.join(TMP, "cfg")
os.environ["SPARKFORGE_SESSIONS_DIR"] = os.path.join(TMP, "sessions")
os.environ["SPARKFORGE_PROVIDERS_LOCAL"] = os.path.join(TMP, "providers.local.yaml")
os.environ["SPARKFORGE_EDITS_DIR"] = os.path.join(TMP, "edits")
os.environ["SPARKFORGE_RUNS_DIR"] = os.path.join(TMP, "runs")
os.environ["SPARKFORGE_DB"] = os.path.join(TMP, "events.db")
sys.path.insert(0, os.path.join(REPO, "src"))

from sparkforge import api_v02, rules  # noqa: E402

results = []


def check(name, ok, detail=""):
    results.append(bool(ok))
    print(("PASS " if ok else "FAIL ") + name + ((" :: " + detail) if detail else ""))


def nocall(fn, *a, **k):
    try:
        return None, fn(*a, **k)
    except Exception as e:  # noqa: BLE001
        return repr(e), None


BAD_TOOLS = [
    {"runtime": {"keepgoing_max": "abc"}},
    {"runtime": {"max_wall_secs": "abc"}},
    {"runtime": {"no_progress_rounds": [1]}},
    {"verifier": {"timeout_secs": "abc"}},
    {"bestofn": {"n": "abc"}},
    {"bestofn": {"min_score": "abc"}},
    {"difficulty": {"easy_n": "abc"}},
    {"difficulty": {"medium_at": "abc"}},
    {"selfevolve": {"min_len": "abc"}},
    {"tool": "web_search", "auto_approve": 123},
]
for body in BAD_TOOLS:
    err, res = nocall(api_v02.update_policy, body)
    check("JAG-251 update_policy(%r) -> clean ok=False" % (body,),
          err is None and isinstance(res, dict) and res.get("ok") is False,
          err or str(res)[:90])

# a VALID settings change still works (written to the temp config)
err, res = nocall(api_v02.update_policy, {"runtime": {"keepgoing_max": 7}})
check("JAG-251 update_policy(valid runtime) -> ok True",
      err is None and res.get("ok") is True, err or str(res))

# ---- rules.save: content is wire data --------------------------------------
err, res = nocall(rules.save, "global", 123)
check("JAG-251 rules.save(content=123) -> no raise + ok True",
      err is None and res.get("ok") is True, err or str(res))
try:
    with open(rules.global_rules_path(), encoding="utf-8") as f:
        disk = f.read()
    check("JAG-251 rules.save wrote a string", disk == "123", repr(disk))
except Exception as e:  # noqa: BLE001
    check("JAG-251 rules.save wrote a string", False, repr(e))

err, res = nocall(rules.save, 123, "x")
check("JAG-251 rules.save(scope=123) -> ok False",
      err is None and res.get("ok") is False, err or str(res))
err, res = nocall(rules.save, "global", None)
check("JAG-251 rules.save(content=None) -> ok True",
      err is None and res.get("ok") is True, err or str(res))

# ---- static guards ---------------------------------------------------------
def read(rel):
    with open(os.path.join(REPO, "src", "sparkforge", rel), encoding="utf-8") as f:
        return f.read()


av = read("api_v02.py")
rv = read("rules.py")
tv = read("tools.py")
sev = read("selfevolve.py")
check("JAG-251 update_policy wraps conversions", "def _update_policy(body):" in av
      and "invalid settings value" in av)
check("JAG-251 rules.save coerces content", "isinstance(content, str)" in rv)
check("i18n rules.py scope error English", "scope must be 'global' or 'project'" in rv)
check("i18n rules.py truncation marker English", "[truncated]" in rv)
check("i18n tools.py verify/promote English",
      "path required for action=verify" in tv and "path required for action=promote" in tv)
check("i18n tools.py selfevolve reason English",
      "repeated tool pattern detected" in tv)
check("i18n selfevolve.py English",
      "generated by selfevolve" in sev and "proposal not verified" in sev)

print("---")
ok = sum(results)
print("%d/%d PASS" % (ok, len(results)))
sys.exit(0 if ok == len(results) else 1)
