#!/usr/bin/env python3
"""Longrun v0.6 — per-run task graph, generated by the LLM (write_todos).

Modern harnesses (Claude Code Agent SDK todo-tracking, Deep Agents write_todos)
keep a *live, per-run* graph of the steps the model itself decided on, instead of
a static global list disconnected from the conversation. This module owns that
graph:

  * one graph per run  → `data/graphs/<run_id>.json`, linked to `session_id`
    and `run_id` (nodes: id, label, status todo|doing|done|blocked|cancelled,
    deps[], evidence[]);
  * the first action of any chat/agent run is a model-generated
    `write_todos` tool call (streamed, NDJSON or nested JSON — never a template);
  * every mutation emits `graph.node.added` / `graph.node.updated` on the feed,
    so WebUI and SparkPulse render the graph live;
  * a node may only become `done` when it carries evidence (command + output);
  * `plan_step` / `complete_plan_step` / `add_task` / `complete_task` from the
    existing agent loops are mapped onto graph nodes.

server.py owns the HTTP surface (`GET /api/runs/<id>/graph`,
`POST /api/runs/<id>/graph/nodes`); this module stays server-agnostic and
imports `server` lazily only to publish events.
"""

import json
import os
import re
import threading
import time
import uuid

from longrun.util.paths import REPO_ROOT as REPO
GRAPH_DIR = os.path.join(os.environ.get("LONGRUN_GRAPH_DIR", os.path.join(REPO, "data")),
                         "graphs")

GRAPH_LOCK = threading.RLock()
# JAG-266: `superseded` is a CLOSED state (not open) meaning "deliberately abandoned",
# carrying a `reason` on the node — the model may close a leftover step this way instead
# of being forced to finish work the user no longer wants.
STATUSES = ("todo", "doing", "done", "blocked", "cancelled", "superseded")
OPEN_STATUSES = ("todo", "doing", "blocked")
CLOSED_STATUSES = ("done", "cancelled", "superseded")

# The model is asked to answer the FIRST action of every run with this tool call.
# Two wire formats are accepted, both stream-friendly:
#   NDJSON:   {"tool":"write_todos"}\n{"label":"...","deps":[]}\n{"label":"...","deps":[0]}
#   nested:   {"tool":"write_todos","todos":[{"label":"...","deps":[]}, ...]}
WRITE_TODOS_PROMPT = (
    "You are the Longrun planner. Your FIRST action for every request is to "
    "call the `write_todos` tool: decompose the current user request into an "
    "ordered task graph of 2-8 steps. This list is PERSISTENT — it is saved, "
    "re-shown to you on every turn, and you must work through every open step. "
    "Respond with ONLY JSON, one object per line (no prose, no markdown):\n"
    '{"tool":"write_todos"}\n'
    '{"label":"<imperative step specific to the request>","status":"todo","deps":[]}\n'
    '{"label":"<next step>","status":"todo","deps":[0]}\n'
    '{"label":"<subtask of step 0>","status":"todo","parent":0}\n'
    "Rules: labels are imperative and mention the actual request (never generic "
    "placeholders); `deps` holds the 0-based indices of prerequisite steps; "
    "`parent` (optional) makes a step a SUBTASK of another; the first step has "
    "no dependencies. A single JSON object with a `todos` array is also accepted."
)


# ------------------------------------------------------------- publishing --

def _publish(kind, **data):
    """Fan out to the harness feed; never let the feed break a run."""
    try:
        from longrun.core import server
        return server.publish(kind, **data)
    except Exception:  # noqa: BLE001
        return None


# ------------------------------------------------------------------ storage --

def _safe_id(key):
    return re.sub(r"[^A-Za-z0-9_.-]", "_", str(key or "unknown"))[:96]


def _path(key):
    return os.path.join(GRAPH_DIR, _safe_id(key) + ".json")


def _read_json(path, default=None):
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:  # noqa: BLE001
        return default


def _write_json(path, obj):
    # JAG-287: a UNIQUE temp name per write. Up to three writers can touch the same
    # session graph (the turn worker, the background planner, the UI node endpoint);
    # a fixed "<path>.tmp" let the first os.replace() rename it away and the second
    # raise FileNotFoundError. Mirrors the JAG-201 fix for session transcripts.
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = "%s.%s.tmp" % (path, uuid.uuid4().hex[:12])
    try:
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=2, ensure_ascii=False)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            try:
                os.remove(tmp)
            except OSError:
                pass


def load(key):
    """Load the graph for `key` (a session id = a task, or a run id) or None."""
    return _read_json(_path(key), None)


def save(graph):
    graph["updated"] = round(time.time(), 3)
    _write_json(_path(graph.get("key") or graph.get("run_id")), graph)
    return graph


def ensure(key, session_id=None, goal=None):
    """Get-or-create the graph for `key`.

    JAG-63: the graph is the ONE persistent task list. In chat it is keyed by
    the SESSION id (one task = one session → it survives across messages,
    compaction and restarts). Agent runs key it by the run id.
    """
    with GRAPH_LOCK:
        g = load(key)
        if g is None:
            g = {"key": key, "run_id": key, "session_id": session_id, "goal": goal,
                 "nodes": [], "plan": 0,
                 "created": round(time.time(), 3),
                 "updated": round(time.time(), 3), "generated": False}
            save(g)
        else:
            changed = False
            if not g.get("key"):
                g["key"] = key
                changed = True
            if not g.get("run_id"):
                g["run_id"] = key
                changed = True
            if "plan" not in g:
                g["plan"] = 0
                changed = True
            if session_id and g.get("session_id") != session_id:
                g["session_id"] = session_id
                changed = True
            if goal and g.get("goal") != goal:
                g["goal"] = goal
                changed = True
            if changed:
                save(g)
        return g


def reset(key):
    """Archive (soft-clear) the task list for `key`. Only a user / new task may
    call this — never the model, so the list never silently disappears."""
    p = _path(key)
    if not os.path.exists(p):
        return {"reset": False, "key": key}
    archived = p + ".reset-%d" % int(time.time())
    try:
        os.replace(p, archived)
    except OSError as e:  # noqa: BLE001
        return {"reset": False, "key": key, "error": str(e)}
    _publish("graph.reset", run=key, session=key, archived=os.path.basename(archived))
    return {"reset": True, "key": key, "archived": os.path.basename(archived)}


def begin_plan(graph):
    """JAG-194: start a NEW task plan on the SAME session graph (no hard reset).

    A finished task used to `reset` the graph (file archived → node ids restarted
    at n1). The transcript's old cards still carried those ids, so after a reload
    they resolved to the NEW nodes (wrong labels) or nested under the wrong step.
    Instead we KEEP every node — ids stay unique for the whole session — and bump
    `plan`; the model prompt + the panel focus on the current plan while the
    transcript keeps its history.
    """
    with GRAPH_LOCK:
        graph["plan"] = int(graph.get("plan", 0)) + 1
        graph["generated"] = False
        save(graph)
        return graph["plan"]


def plan_nodes(graph):
    """Nodes of the CURRENT plan (all nodes when none is tagged / plan 0)."""
    if not graph:
        return []
    cur = graph.get("plan", 0)
    return [n for n in graph.get("nodes", []) if n.get("plan", 0) == cur]


def render_todos(graph, limit=12, compact=False):
    """Compact text block of the persistent task list, for prompt injection.

    JAG-194: only the CURRENT plan's nodes are shown — old, finished plans stay in
    the graph (so the transcript keeps resolving their ids) but must not be
    re-fed to the model as if they were still to do.

    JAG-273: `compact=True` (used for the always-on `state` prompt section) lists
    only the OPEN steps plus a count of the closed ones, and drops the trailing
    ownership paragraph — that rule already lives in the static `task-policy`
    section, so repeating it on every turn was pure duplicated tokens. The default
    (full) rendering is kept for the `todo` tool and the legacy ownership contract.
    """
    if not graph or not graph.get("nodes"):
        return ""
    nodes = plan_nodes(graph) or graph.get("nodes", [])
    open_nodes = [n for n in nodes if n.get("status") in OPEN_STATUSES]
    open_n, total_n = len(open_nodes), len(nodes)
    if compact:
        lines = ["TASK LIST (%d open / %d total):" % (open_n, total_n)]
        show = open_nodes[:limit]
    else:
        lines = ["TASK LIST (persistent — this is YOUR todo list; it survives "
                 "compaction and restarts; %d open / %d total):" % (open_n, total_n)]
        show = nodes[:limit]
    for n in show:
        mark = {"todo": "[ ]", "doing": "[>]", "done": "[x]",
                "blocked": "[!]", "cancelled": "[-]",
                "superseded": "[~]"}.get(n.get("status"), "[ ]")
        indent = "    " if n.get("parent") else "  "
        extra = ""
        if n.get("status") == "superseded" and n.get("reason"):
            extra = "  (superseded: %s)" % n.get("reason")
        lines.append("%s%s %s (%s)%s" % (indent, mark, n.get("label", ""), n.get("id"), extra))
    if compact:
        if total_n > open_n:
            lines.append("  (+%d closed — call the `todo` tool for the full list)"
                         % (total_n - open_n))
        if not open_n:
            lines.append("  (no open steps — the plan is complete)")
        return "\n".join(lines)
    if open_n:
        lines.append("This list is YOURS: keep it current — set a step [>] 'doing' "
                     "before you start it, and [x] 'done' with evidence when it is "
                     "REALLY finished. NEVER redo a step already marked [x]. If a step "
                     "is no longer wanted, close it as [~] 'superseded' WITH a reason "
                     "(update_todos). Add a step if the goal grows.")
    return "\n".join(lines)


def all_done(graph):
    """True when the list has nodes and none are still open."""
    nodes = graph.get("nodes", []) if graph else []
    if not nodes:
        return False
    return all(n.get("status") in CLOSED_STATUSES for n in nodes)



def counts(graph):
    c = {s: 0 for s in STATUSES}
    for n in graph.get("nodes", []):
        c[n.get("status", "todo")] = c.get(n.get("status", "todo"), 0) + 1
    return c


def public(graph):
    """UI-friendly shape: nodes + counts + a coarse graph status."""
    if not graph:
        return None
    c = counts(graph)
    total = len(graph.get("nodes", []))
    closed = sum(c.get(s, 0) for s in CLOSED_STATUSES)
    if total and closed == total:
        status = "done"
    elif any(n.get("status") == "blocked" for n in graph.get("nodes", [])):
        status = "blocked"
    elif c.get("doing"):
        status = "doing"
    elif total:
        status = "todo"
    else:
        status = "empty"
    return {**graph, "counts": c, "status": status, "node_count": total}


def _next_id(graph):
    used = {n["id"] for n in graph.get("nodes", [])}
    i = 1
    while ("n%d" % i) in used:
        i += 1
    return "n%d" % i


def _evidence_entry(text, **extra):
    entry = {"ts": round(time.time(), 3), "text": str(text)[:4000]}
    entry.update({k: v for k, v in extra.items() if v is not None})
    return entry


def _has_evidence(node):
    return bool([e for e in (node.get("evidence") or []) if (e.get("text") or "").strip()])


def _has_observed(node):
    """True when the node carries at least one OBSERVED (environment-proof) entry."""
    return bool([e for e in (node.get("evidence") or []) if e.get("observed")])


# ------------------------------------------------------------ node mutation --

def add_node(graph, label, deps=None, status="todo", evidence=None, node_id=None,
             source="model", parent=None, child_run_id=None, requires_proof=False):
    """Append a node; emits `graph.node.added`. `done` requires evidence.

    JAG-63: `parent` (a node id) turns a node into a SUBTASK of another step,
    so the task list can carry hierarchy, not just flat `deps`.
    JAG-206 (RDD P1): `requires_proof` marks a RISKY step that may only be closed
    with an OBSERVED (environment-proof) evidence entry, not a bare claim.
    """
    label = str(label or "").strip()[:200]
    if not label:
        raise ValueError("label required")
    if status not in STATUSES:
        raise ValueError("bad status %r (expected one of %s)" % (status, ", ".join(STATUSES)))
    deps = [str(d) for d in (deps or []) if str(d)]
    ev = []
    if evidence:
        ev = list(evidence) if isinstance(evidence, list) else [_evidence_entry(evidence)]
    if status == "done" and not ev:
        raise ValueError("evidence required for a node in status 'done'")
    if status == "done" and requires_proof and not _has_observed({"evidence": ev}):
        raise ValueError("environment proof required to mark a risky node done")
    # JAG-195: assign the id INSIDE the lock. `_next_id` scans the current nodes,
    # so computing it before the lock let concurrent add_node calls read the same
    # "next" id and append duplicates (20 threads -> only 3 unique ids).
    with GRAPH_LOCK:
        node = {"id": node_id or _next_id(graph), "label": label, "status": status,
                "deps": deps, "parent": str(parent) if parent else None, "evidence": ev,
                "requires_proof": bool(requires_proof),
                "plan": graph.get("plan", 0),
                # JAG-299: the job (JN) this node was created for, if any — lets the UI
                # attribute a todo to its job instead of one undifferentiated list.
                "jid": graph.get("jid"),
                # JAG-324: the SUBJOB (JN.j) this node belongs to, if any. A job's work
                # is split into numbered subjobs, each bound to ONE agent (= session);
                # the todos an agent creates while working a subjob carry its id, so a
                # subjob "embraces" a subset of that agent's todos.
                "subjob": graph.get("subjob"),
                "source": source, "child_run_id": child_run_id,
                "created": round(time.time(), 3), "updated": round(time.time(), 3)}
        graph["nodes"].append(node)
        save(graph)
        _index = len(graph["nodes"]) - 1
        _total = len(graph["nodes"])
    _publish("graph.node.added", run=graph["run_id"], session=graph.get("session_id"),
             node=node, index=_index, total=_total)
    return node


def find(graph, node_id=None, label=None):
    for n in graph.get("nodes", []):
        if node_id and n["id"] == node_id:
            return n
    if label:
        for n in graph.get("nodes", []):
            if n["label"].lower() == str(label).strip().lower():
                return n
    return None


# JAG-278: phrases that CONTRADICT a 'superseded' — they say the work is still
# open/pending, so the step is being force-closed, not genuinely abandoned.
_VAGUE_REASON = (
    "resta aperto", "resta aperta", "rimane aperto", "rimane aperta", "restano aperti",
    "ancora aperto", "ancora aperti", "resta da", "rimane da", "restano da",
    "non completat", "non conclus", "da completare", "da aggiornare",
    "remains open", "still open", "still pending", "remains to be", "not complet",
)


def _is_vague_reason(reason):
    """True when a 'superseded' reason actually says the work is STILL pending."""
    r = str(reason or "").strip().lower()
    return any(p in r for p in _VAGUE_REASON)


def update_node(graph, node_id, evidence=None, source=None, **fields):
    """Patch a node; emits `graph.node.updated`. Evidence is mandatory for `done`."""
    node = find(graph, node_id)
    if node is None:
        raise KeyError("node %r not found" % node_id)
    changes = {}
    if "status" in fields and fields["status"] is not None:
        st = fields["status"]
        if st not in STATUSES:
            raise ValueError("bad status %r (expected one of %s)" % (st, ", ".join(STATUSES)))
        changes["status"] = st
    if fields.get("label"):
        changes["label"] = str(fields["label"])[:200]
    if fields.get("deps") is not None:
        changes["deps"] = [str(d) for d in fields["deps"]]
    if fields.get("reason") is not None:
        # JAG-266: the why for a `superseded` (or otherwise closed) step.
        changes["reason"] = str(fields["reason"])[:300]
    if source:
        changes["source"] = source
    if evidence:
        entries = evidence if isinstance(evidence, list) else [_evidence_entry(evidence)]
        changes["evidence"] = list(node.get("evidence") or []) + entries
    # A node can only be marked done with evidence on the node (old or new).
    if changes.get("status") == "done":
        probe = {**node, **changes}
        if not _has_evidence(probe):
            raise ValueError("evidence required to mark node %s done" % node_id)
        # JAG-206 (RDD P1): a risky step needs OBSERVED (environment) proof.
        if probe.get("requires_proof") and not _has_observed(probe):
            raise ValueError("environment proof required to mark risky node %s done"
                             % node_id)
    # JAG-269: closing a step as 'superseded' REQUIRES a reason (the "why"), the
    # same way 'done' requires evidence. A todo never leaves the list unexplained:
    # the reason is a FIELD of the node object, addressed by its id — not free text
    # that can be skipped.
    if changes.get("status") == "superseded":
        probe = {**node, **changes}
        reason = str(probe.get("reason") or "").strip()
        if not reason:
            raise ValueError("a reason is required to mark node %s 'superseded'" % node_id)
        # JAG-278: the reason must justify the ABANDONMENT, not describe work still
        # wanted ("the work remains open"). That is a force-close of an open step,
        # exactly what the operator forbade ("you cannot eat tasks with no reason").
        if _is_vague_reason(reason):
            raise ValueError(
                "the 'superseded' reason for node %s must say WHY the step is no longer "
                "needed; it read as still-pending (%r). If the work is still wanted but "
                "not now, LEAVE IT OPEN instead." % (node_id, reason[:120]))
    with GRAPH_LOCK:
        node.update(changes)
        node["updated"] = round(time.time(), 3)
        save(graph)
    _publish("graph.node.updated", run=graph["run_id"], session=graph.get("session_id"),
             node=node, changes=sorted(changes.keys()))
    return node


def record_delegation(graph, node_id, ok, error=None, subagent_id=None):
    """JAG-320: durably remember the OUTCOME of a subagent delegation on a node.

    Observed live: a coordinator spawned a subagent for a step, the subagent TIMED
    OUT (exit 1), and the model then closed that step as `done` with invented
    evidence — the harness accepted it because the only gate is a non-empty
    evidence string. Storing the outcome ON the node (not only in a server-process
    dict) makes the guard survive restarts and long gaps between the failure and
    the claim, and keeps it scoped to the ONE delegated step: a failed delegation
    on one step must not block an unrelated step. `ok=True` (a successful retry)
    CLEARS the marker so the step can be closed normally.
    """
    node = find(graph, node_id)
    if node is None:
        return None
    with GRAPH_LOCK:
        if ok:
            node.pop("delegation", None)
        else:
            node["delegation"] = {
                "ok": False,
                "error": str(error or "subagent failed")[:300],
                "subagent_id": subagent_id,
                "ts": round(time.time(), 3),
            }
        node["updated"] = round(time.time(), 3)
        save(graph)
    _publish("graph.node.updated", run=graph["run_id"], session=graph.get("session_id"),
             node=node, changes=["delegation"])
    return node


def clear_delegation(graph, node_id):
    """JAG-320: consume a failed-delegation marker once it has done its job.

    The refusal is ONE-SHOT: after the guard fires once on a `done` attempt the
    marker is dropped, so a genuine second attempt — a retry that succeeded, or
    the model doing the work itself — is never blocked forever.
    """
    node = find(graph, node_id)
    if node is None or "delegation" not in node:
        return node
    with GRAPH_LOCK:
        node.pop("delegation", None)
        node["updated"] = round(time.time(), 3)
        save(graph)
    _publish("graph.node.updated", run=graph["run_id"], session=graph.get("session_id"),
             node=node, changes=["delegation"])
    return node


def complete_node(graph, node_id=None, label=None, evidence=None, source=None,
                  observed=False):
    """Mark a node done (creating it from the label when it is unknown).

    JAG-206 (RDD P1): `observed=True` attaches an environment-proof evidence
    entry, which is what a `requires_proof` node needs to close.
    """
    node = find(graph, node_id, label)
    if node is None and label:
        node = add_node(graph, label, source=source or "action")
    if node is None:
        raise KeyError("node %r not found" % (node_id or label))
    if isinstance(evidence, list):
        entries = evidence
    else:
        entries = [_evidence_entry(evidence or "completed by agent",
                                   **({"observed": True} if observed else {}))]
    return update_node(graph, node["id"], status="done", evidence=entries, source=source)


def cancel_node(graph, node_id):
    """Cancel (soft-delete) a node — never silently drop history."""
    return update_node(graph, node_id, status="cancelled", source="cancel")


def audit_node(graph, node_id):
    """Read-only verdict on a node (RDD P1 / JAG-206).

    A `requires_proof` (risky) node is only `ok` once it carries an OBSERVED
    (environment-proof) evidence entry. Never mutates the graph.
    """
    node = find(graph, node_id)
    if node is None:
        return {"node": node_id, "ok": False, "has_proof": False,
                "requires_proof": False, "status": None,
                "observed_entries": [], "reason": "unknown_node"}
    obs = [e for e in (node.get("evidence") or []) if e.get("observed")]
    has = bool(obs)
    requires = bool(node.get("requires_proof"))
    reason = "ok"
    if requires and not has:
        reason = "missing_environment_proof"
    return {"node": node_id, "ok": (has or not requires), "has_proof": has,
            "requires_proof": requires, "status": node.get("status"),
            "observed_entries": [str(e.get("text") or "")[:200] for e in obs][:5],
            "reason": reason}


def apply_write_todos(graph, todos, source="model:write_todos", index_map=None, start=0):
    """Turn a parsed `write_todos` payload into graph nodes (order preserved).

    `deps` are 0-based indices into the todo list; `index_map` (index → node id)
    lets callers feed the list one line at a time and still resolve deps.
    """
    added = []
    index_map = index_map if index_map is not None else {}
    for i, item in enumerate(todos or []):
        if isinstance(item, str):
            item = {"label": item}
        if not isinstance(item, dict):
            continue
        label = item.get("label") or item.get("title") or item.get("task")
        if not label:
            continue
        deps = []
        for d in (item.get("deps") or item.get("depends_on") or []):
            if isinstance(d, bool):
                continue
            if isinstance(d, int) and d in index_map:
                deps.append(index_map[d])
            elif isinstance(d, str) and d.isdigit() and int(d) in index_map:
                deps.append(index_map[int(d)])
            elif isinstance(d, str) and d:
                # JAG-269: a string dep may be a node ID ("n3", id-first) or a label.
                existing = find(graph, node_id=d) or find(graph, label=d)
                if existing:
                    deps.append(existing["id"])
        status = item.get("status") if item.get("status") in STATUSES else "todo"
        evidence = item.get("evidence")
        if status == "done" and not evidence:
            status = "todo"
        # JAG-63: `parent` may be a 0-based index into this list or a node id.
        parent = item.get("parent")
        if isinstance(parent, bool):
            parent = None
        if isinstance(parent, int) and parent in index_map:
            parent = index_map[parent]
        elif isinstance(parent, str) and parent.isdigit() and int(parent) in index_map:
            parent = index_map[int(parent)]
        node = add_node(graph, label, deps=deps, status=status, evidence=evidence,
                        source=source, parent=parent,
                        requires_proof=bool(item.get("requires_proof")))
        index_map[start + i] = node["id"]
        added.append(node)
    graph["generated"] = True
    save(graph)
    return added


def _norm_label(s):
    return " ".join(str(s or "").lower().split())


def supersede_open(graph, keep_labels):
    """JAG-177: a re-plan REPLACES the plan — cancel every OPEN node whose label is
    not in `keep_labels`. `done`/`cancelled` history is never touched, so nothing is
    lost. This is what stops re-planning from ACCUMULATING a wall of obsolete,
    overlapping steps (session `test`: 27 nodes from 3 re-plans). Returns the ids
    that were cancelled."""
    keep = {_norm_label(x) for x in (keep_labels or [])}
    cancelled = []
    for n in list(graph.get("nodes", [])):
        if n.get("status") not in OPEN_STATUSES:
            continue
        if keep and _norm_label(n.get("label")) in keep:
            continue
        try:
            cancelled.append(update_node(graph, n["id"], status="cancelled",
                                         source="harness:supersede")["id"])
        except (KeyError, ValueError):
            continue
    return cancelled


def enforce_single_doing(graph, keep_id=None):
    """JAG-177: at most ONE node may be `doing` (the standard rule). Demote the
    extras to `todo`. Returns the ids that were demoted."""
    doing = [n for n in graph.get("nodes", []) if n.get("status") == "doing"]
    if len(doing) <= 1:
        return []
    keep = keep_id or max(doing, key=lambda n: n.get("updated") or 0)["id"]
    demoted = []
    for n in doing:
        if n["id"] == keep:
            continue
        try:
            demoted.append(update_node(graph, n["id"], status="todo",
                                       source="harness:single-doing")["id"])
        except (KeyError, ValueError):
            continue
    return demoted


def finalize(graph, evidence, only_open=True):
    """At run end, close every open node with evidence (acceptance: all done)."""
    closed = []
    for n in list(graph.get("nodes", [])):
        if only_open and n.get("status") not in OPEN_STATUSES:
            continue
        try:
            closed.append(update_node(graph, n["id"], status="done",
                                      evidence=evidence, source="run-finalize"))
        except (KeyError, ValueError):
            continue
    return closed


# ----------------------------------------------- model-generated first action --

def _iter_json_objects(text):
    """All balanced top-level `{...}` objects in `text` (order preserved)."""
    objs, depth, start, in_str, esc = [], 0, None, False, False
    for i, ch in enumerate(text):
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
            continue
        if ch == '"':
            in_str = True
        elif ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            if depth > 0:
                depth -= 1
                if depth == 0 and start is not None:
                    try:
                        objs.append(json.loads(text[start:i + 1]))
                    except Exception:  # noqa: BLE001
                        pass
    return objs


def parse_todos(text):
    """Parse `write_todos` output from NDJSON lines and/or a nested JSON object."""
    todos, saw_tool = [], False
    for obj in _iter_json_objects(text or ""):
        if not isinstance(obj, dict):
            continue
        if obj.get("tool") == "write_todos" or "todos" in obj:
            saw_tool = True
            nested = obj.get("todos")
            if isinstance(nested, list):
                todos.extend(nested)
            continue
        if obj.get("label") or obj.get("title") or obj.get("task"):
            todos.append(obj)
    return todos, saw_tool


class _TodoStream:
    """Incremental NDJSON consumer: emits each todo the moment its line lands."""

    def __init__(self, graph, on_event=None, source="model:write_todos",
                 skip_existing=False):
        self.graph = graph
        self.on_event = on_event
        self.source = source
        self.skip_existing = skip_existing
        self.index_map = {}   # todo index → node id (deps resolve across lines)
        self.count = 0
        self.buf = ""
        self.got = False
        self.added = []

    def _emit(self, node):
        self.added.append(node)
        if self.on_event:
            try:
                self.on_event("graph.node.added", run=self.graph["run_id"],
                              session=self.graph.get("session_id"), node=node,
                              index=len(self.added) - 1, total=len(self.added))
            except Exception:  # noqa: BLE001
                pass

    def _consume(self, line):
        line = (line or "").strip().rstrip(",")
        if not line.startswith("{"):
            return
        try:
            obj = json.loads(line)
        except Exception:  # noqa: BLE001
            return
        if not isinstance(obj, dict):
            return
        if isinstance(obj.get("todos"), list):
            nested = self._dedupe(obj["todos"])
            for t in apply_write_todos(self.graph, nested, self.source,
                                       index_map=self.index_map, start=self.count):
                self._emit(t)
            self.count += len(nested)
            return
        if obj.get("tool") == "write_todos" and not (
                obj.get("label") or obj.get("title") or obj.get("task")):
            return
        if obj.get("label") or obj.get("title") or obj.get("task"):
            for t in apply_write_todos(self.graph, self._dedupe([obj]), self.source,
                                       index_map=self.index_map, start=self.count):
                self._emit(t)
            self.count += 1

    def _dedupe(self, todos):
        # re-plan: never duplicate a label that is already on the graph
        return _missing(self.graph, todos) if self.skip_existing else todos

    def feed(self, text):
        """Consume a stream *delta*; each complete ("\\n"-terminated) line is a todo."""
        text = text or ""
        if text:
            self.got = True
        self.buf += text
        lines = self.buf.split("\n")
        self.buf = lines.pop()
        for line in lines:
            self._consume(line)
        return self.added

    def flush(self):
        """Flush whatever is left in the buffer (no trailing newline)."""
        tail, self.buf = self.buf, ""
        if tail.strip():
            self._consume(tail)
        return self.added


def _missing(graph, todos):
    """Drop todos whose label already exists on the CURRENT plan (idempotent).

    JAG-196: dedupe against the current plan only — with every plan's nodes kept
    (JAG-194), comparing against the whole graph made a NEW task that reuses a
    label ("run pwd" again) create no nodes at all.
    """
    seen = {n["label"].strip().lower()
            for n in (plan_nodes(graph) or graph.get("nodes", []))}
    out = []
    for t in todos or []:
        label = t if isinstance(t, str) else (t.get("label") or t.get("title") or t.get("task"))
        key = str(label or "").strip().lower()
        if key and key not in seen:
            seen.add(key)
            out.append(t)
    return out


def generate_from_model(run_id, goal, session_id=None, model=None, on_event=None,
                        cancel=None):
    """First action of the run: ask the model for a `write_todos` call.

    Streams the reply and adds each node to the graph as soon as its line is
    complete, publishing `graph.node.added` live. Returns (graph, added_nodes).
    If the graph already has nodes the first action already ran → no-op.

    `cancel` (JAG-197) makes the planner model call abortable: without it a Stop
    during planning was ignored and the turn hung (the session stayed pinned in
    _ACTIVE_CHAT) until the router timeout.
    """
    from longrun.core import server as srv
    graph = ensure(run_id, session_id=session_id, goal=goal)
    if plan_nodes(graph):
        return graph, []
    stream = _TodoStream(graph, on_event=on_event)
    msgs = [{"role": "system", "content": srv.SYSTEM_PROMPT + "\n\n" + WRITE_TODOS_PROMPT},
            {"role": "user", "content": goal}]
    m = model
    if not m:
        try:
            from longrun.model import routing
            m = routing.pick("planner")
        except Exception:  # noqa: BLE001
            m = None
    m = m or srv.default_model()

    def on_delta(channel, text):
        if channel == "think" or not text:
            return
        try:
            stream.feed(text)
        except Exception:  # noqa: BLE001
            pass

    answer, _think = srv._router_stream(msgs, m, on_delta, cancel=cancel)
    if cancel is not None and cancel():
        # JAG-197: the run was aborted mid-planning — add nothing.
        return graph, []
    if not stream.got:  # no deltas (non-streaming path) → consume the answer once
        stream.feed(answer)
    stream.flush()
    if not stream.added:  # pretty-printed / nested JSON that never formed a line
        for node in apply_write_todos(graph, _missing(graph, parse_todos(answer)[0])):
            stream._emit(node)
    graph["generated"] = graph.get("generated") or bool(stream.added)
    save(graph)
    _publish("graph.generated", run=graph["run_id"], session=graph.get("session_id"),
             goal=goal, nodes=len(graph.get("nodes", [])), model=m)
    return graph, stream.added


def replan_from_model(graph, note=None, model=None, on_event=None):
    """Incremental re-plan: the model proposes only the steps still missing.

    Used by `POST /api/runs/<id>/graph/nodes {action:"replan"}` when the request
    changes or a step turns out to be blocked. Existing nodes are preserved.
    """
    from longrun.core import server as srv
    existing = [n["label"] for n in graph.get("nodes", []) if n.get("status") != "cancelled"]
    prompt = (WRITE_TODOS_PROMPT + "\n\nThe task graph already contains: " +
              json.dumps(existing, ensure_ascii=False) +
              "\nEmit ONLY the NEW steps still missing (never repeat an existing label).")
    msgs = [{"role": "system", "content": srv.SYSTEM_PROMPT + "\n\n" + prompt},
            {"role": "user", "content": note or graph.get("goal") or "continue"}]
    m = model
    if not m:
        try:
            from longrun.model import routing
            m = routing.pick("planner")
        except Exception:  # noqa: BLE001
            m = None
    m = m or srv.default_model()
    stream = _TodoStream(graph, on_event=on_event, source="model:replan",
                         skip_existing=True)

    def on_delta(channel, text):
        if channel != "think" and text:
            try:
                stream.feed(text)
            except Exception:  # noqa: BLE001
                pass

    answer, _think = srv._router_stream(msgs, m, on_delta)
    if not stream.got:
        stream.feed(answer)
    stream.flush()
    if not stream.added:
        for node in apply_write_todos(graph, _missing(graph, parse_todos(answer)[0]),
                                      "model:replan"):
            stream._emit(node)
    save(graph)
    _publish("graph.replanned", run=graph["run_id"], session=graph.get("session_id"),
             added=len(stream.added), nodes=len(graph.get("nodes", [])))
    return stream.added


# --------------------------------------------- existing-action → node mapping --

def map_action(run_id, act, observation=None, session_id=None, goal=None):
    """Map a legacy agent action onto the run graph.

    plan_step/complete_plan_step/add_task/complete_task → nodes + status, and
    `write_todos` → the full model-generated graph. Returns the touched node
    (or None).
    """
    action = (act or {}).get("action")
    if action not in ("plan_step", "complete_plan_step", "add_task", "complete_task",
                      "write_todos"):
        return None
    graph = ensure(run_id, session_id=session_id, goal=goal)
    evidence = observation or None
    if action == "write_todos":
        todos = act.get("todos")
        if isinstance(todos, str):
            todos, _ = parse_todos(todos)
        return apply_write_todos(graph, todos or [])
    label = act.get("title") or act.get("label") or act.get("detail")
    if action in ("plan_step", "add_task"):
        if not label:
            return None
        return add_node(graph, label, source="action:" + action)
    # completion actions
    node = find(graph, node_id=act.get("id"), label=label)
    try:
        return complete_node(graph, node_id=act.get("id"), label=label,
                             evidence=evidence or "completed: %s" % (label or act.get("id")),
                             source="action:" + action)
    except (KeyError, ValueError):
        return None

